package GUI;

import java.text.SimpleDateFormat;
import java.util.Calendar;

public class NewTripGUI extends javax.swing.JFrame {

    private main.Users u;
    private carpoolapp.CarPoolDB cpdb;

    /**
     * Creates new form LoginGUI
     */

    public NewTripGUI() {
        initComponents();
        u = new main.Users("null", "null", "null", "null", "null", "null", "null", "null", 0, 0);

        nameLbl.setText(u.getUsername());
    }

    public NewTripGUI(main.Users user) {
        initComponents();
        u = user;

        nameLbl.setText(u.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        headerPnl = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        nameLbl = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        departureLbl = new javax.swing.JLabel();
        arrivalLbl = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        daptDateLbl = new javax.swing.JLabel();
        deptTimeLbl = new javax.swing.JLabel();
        arrDateLbl = new javax.swing.JLabel();
        arrTimeLbl = new javax.swing.JLabel();
        noOfSeatsLbl = new javax.swing.JLabel();
        priceLbl = new javax.swing.JLabel();
        departureTf = new javax.swing.JTextField();
        arrivalTf = new javax.swing.JTextField();
        distanceTf = new javax.swing.JTextField();
        deptDateTf = new javax.swing.JTextField();
        deptMonthTf = new javax.swing.JTextField();
        deptYearTf = new javax.swing.JTextField();
        deptHourTf = new javax.swing.JTextField();
        deptMinsTf = new javax.swing.JTextField();
        arrDateTf = new javax.swing.JTextField();
        arrHourTf = new javax.swing.JTextField();
        arrMonthTf = new javax.swing.JTextField();
        arrMinsTf = new javax.swing.JTextField();
        arrYearTf = new javax.swing.JTextField();
        noOfSeatsTf = new javax.swing.JTextField();
        priceTf = new javax.swing.JTextField();
        heading1Lbl = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        luggageCB = new javax.swing.JCheckBox();
        smokingCB = new javax.swing.JCheckBox();
        petsCB = new javax.swing.JCheckBox();
        chattyCB = new javax.swing.JCheckBox();
        musicLoverCB = new javax.swing.JCheckBox();
        descriptionLbl = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionTA = new javax.swing.JTextArea();
        preferencesLbl = new javax.swing.JLabel();
        addTrip = new javax.swing.JButton();
        warningLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(400, 660));
        setMinimumSize(new java.awt.Dimension(400, 660));
        setPreferredSize(new java.awt.Dimension(400, 660));
        setSize(new java.awt.Dimension(400, 660));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(400, 640));

        headerPnl.setBackground(new java.awt.Color(179, 255, 179));
        headerPnl.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        headerPnl.setMaximumSize(new java.awt.Dimension(400, 100));
        headerPnl.setMinimumSize(new java.awt.Dimension(400, 100));
        headerPnl.setPreferredSize(new java.awt.Dimension(400, 100));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/carduill.png"))); // NOI18N
        jLabel2.setMaximumSize(new java.awt.Dimension(254, 154));

        javax.swing.GroupLayout headerPnlLayout = new javax.swing.GroupLayout(headerPnl);
        headerPnl.setLayout(headerPnlLayout);
        headerPnlLayout.setHorizontalGroup(
            headerPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        headerPnlLayout.setVerticalGroup(
            headerPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPnlLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        nameLbl.setMaximumSize(new java.awt.Dimension(400, 400));

        logoutBtn.setBackground(new java.awt.Color(0, 153, 204));
        logoutBtn.setForeground(new java.awt.Color(254, 254, 254));
        logoutBtn.setText("LOGOUT");
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        departureLbl.setText("Leaving from");

        arrivalLbl.setText("Travelling to");

        jLabel1.setText("Distance (in kms)");

        daptDateLbl.setText("Date");

        deptTimeLbl.setText("Time");

        arrDateLbl.setText("Date");

        arrTimeLbl.setText("Time");

        noOfSeatsLbl.setText("No. of seats available");

        priceLbl.setText("Price per seat");

        deptDateTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptDateTfActionPerformed(evt);
            }
        });

        deptYearTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptYearTfActionPerformed(evt);
            }
        });

        deptHourTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptHourTfActionPerformed(evt);
            }
        });

        deptMinsTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deptMinsTfActionPerformed(evt);
            }
        });

        arrDateTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrDateTfActionPerformed(evt);
            }
        });

        arrHourTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrHourTfActionPerformed(evt);
            }
        });

        arrMonthTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrMonthTfActionPerformed(evt);
            }
        });

        arrMinsTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrMinsTfActionPerformed(evt);
            }
        });

        arrYearTf.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                arrYearTfActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(priceTf, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(departureLbl)
                                .addComponent(arrivalLbl))
                            .addGap(34, 34, 34)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(deptTimeLbl)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(departureTf, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(daptDateLbl))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(arrivalTf, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(arrDateLbl))
                                        .addComponent(arrTimeLbl))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(deptDateTf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(deptMonthTf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(deptYearTf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addComponent(deptHourTf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(deptMinsTf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel2Layout.createSequentialGroup()
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(arrDateTf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(arrHourTf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addGroup(jPanel2Layout.createSequentialGroup()
                                                    .addComponent(arrMonthTf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                    .addComponent(arrYearTf, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addComponent(arrMinsTf, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGap(116, 116, 116)
                                    .addComponent(priceLbl))))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(distanceTf, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(noOfSeatsLbl)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(noOfSeatsTf))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(departureLbl)
                    .addComponent(daptDateLbl)
                    .addComponent(departureTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deptDateTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deptMonthTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deptYearTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(deptTimeLbl)
                    .addComponent(deptMinsTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deptHourTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arrYearTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arrMonthTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arrDateTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arrDateLbl)
                    .addComponent(arrivalTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arrivalLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(arrMinsTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arrHourTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(arrTimeLbl))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(distanceTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(noOfSeatsLbl)
                    .addComponent(noOfSeatsTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(priceLbl)
                    .addComponent(priceTf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        heading1Lbl.setText("Let's set up the trip!");

        luggageCB.setText("Luggage allowed");

        smokingCB.setText("Smoking allowed");

        petsCB.setText("Pets allowed");

        chattyCB.setText("Chatty driver");

        musicLoverCB.setText("Likes music");

        descriptionLbl.setText("A message for your fellow passengers");

        descriptionTA.setColumns(20);
        descriptionTA.setRows(5);
        jScrollPane1.setViewportView(descriptionTA);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(luggageCB)
                                    .addComponent(musicLoverCB))
                                .addGap(105, 105, 105)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(chattyCB)
                                    .addComponent(smokingCB)))
                            .addComponent(petsCB)
                            .addComponent(descriptionLbl))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(luggageCB)
                    .addComponent(smokingCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(petsCB)
                    .addComponent(chattyCB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(musicLoverCB)
                .addGap(18, 18, 18)
                .addComponent(descriptionLbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        preferencesLbl.setText("Additional info about the trip");

        addTrip.setBackground(new java.awt.Color(0, 153, 204));
        addTrip.setText("POST A TRIP");
        addTrip.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTripActionPerformed(evt);
            }
        });

        warningLbl.setForeground(new java.awt.Color(255, 0, 0));
        warningLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(headerPnl, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(nameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(218, 218, 218))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(heading1Lbl)
                    .addComponent(preferencesLbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(warningLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(addTrip)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(headerPnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(nameLbl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(heading1Lbl)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(preferencesLbl)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(addTrip))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(warningLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(27, 27, 27)
                .addComponent(logoutBtn)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        //switch to the Login screen
        GUI.LoginGUI l = new GUI.LoginGUI();

        // Get the size of the active window
        int sizeH = this.getSize().height;
        int sizeW = this.getSize().width;

        // Get the location of the active window
        int currX = this.getLocation().x;
        int currY = this.getLocation().y;

        // Set the size of the new window
        l.setSize(sizeW, sizeH);

        // Set the location of the new window
        l.setLocation(currX, currY);

        // Hide the active window, show the new window
        this.dispose();

        // make it visible
        l.setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void deptDateTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptDateTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptDateTfActionPerformed

    private void deptYearTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptYearTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptYearTfActionPerformed

    private void deptHourTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptHourTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptHourTfActionPerformed

    private void deptMinsTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deptMinsTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deptMinsTfActionPerformed

    private void arrDateTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrDateTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrDateTfActionPerformed

    private void arrHourTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrHourTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrHourTfActionPerformed

    private void arrMonthTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrMonthTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrMonthTfActionPerformed

    private void arrMinsTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrMinsTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrMinsTfActionPerformed

    private void arrYearTfActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_arrYearTfActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_arrYearTfActionPerformed

    private void addTripActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTripActionPerformed

        cpdb = new carpoolapp.CarPoolDB();

        warningLbl.setText("");

        if (departureTf.getText().equals("") || deptDateTf.getText().equals("") || deptMonthTf.getText().equals("") || deptYearTf.getText().equals("")
                || deptHourTf.getText().equals("") || deptMinsTf.getText().equals("") || arrDateTf.getText().equals("") || arrMonthTf.getText().equals("")
                || arrYearTf.getText().equals("") || arrHourTf.getText().equals("") || arrMinsTf.getText().equals("") || distanceTf.getText().equals("")
                || noOfSeatsTf.getText().equals("") || priceTf.getText().equals("") || descriptionTA.getText().equals("")) {
            warningLbl.setText("All the fields need to be filled out.");
        }

        else if (!(deptDateTf.getText().length() == 2) || !(deptMonthTf.getText().length() == 2) || !(deptYearTf.getText().length() == 4) || 
                !(deptHourTf.getText().length() == 2) || !(deptMinsTf.getText().length() == 2) || !(arrDateTf.getText().length() == 2) || 
                !(arrMonthTf.getText().length() == 2) || !(arrYearTf.getText().length() == 4) || 
                !(arrHourTf.getText().length() == 2) || !(arrMinsTf.getText().length() == 2)) {
            warningLbl.setText("Incorrect time and date format.");
        }
        
           
        else if ((deptDateTf.getText().equals("29") && deptMonthTf.getText().equals("02")) || (deptDateTf.getText().equals("30") && deptMonthTf.getText().equals("02"))
                || (deptDateTf.getText().equals("31") && deptMonthTf.getText().equals("02")) || (deptDateTf.getText().equals("31") && deptMonthTf.getText().equals("04"))
                || (deptDateTf.getText().equals("31") && deptMonthTf.getText().equals("06")) || (deptDateTf.getText().equals("31") && deptMonthTf.getText().equals("09"))
                || (deptDateTf.getText().equals("31") && deptMonthTf.getText().equals("11")) || (arrDateTf.getText().equals("29") && arrMonthTf.getText().equals("02"))
                || (arrDateTf.getText().equals("30") && arrMonthTf.getText().equals("02")) || (arrDateTf.getText().equals("31") && arrMonthTf.getText().equals("02"))
                || (arrDateTf.getText().equals("31") && arrMonthTf.getText().equals("04")) || (arrDateTf.getText().equals("31") && arrMonthTf.getText().equals("06"))
                || (arrDateTf.getText().equals("31") && arrMonthTf.getText().equals("09")) || (arrDateTf.getText().equals("31") && arrMonthTf.getText().equals("11"))) {
            warningLbl.setText("Incorrect date format.");
        }
               

        else if ((deptDateTf.getText().equals("29") && deptMonthTf.getText().equals("02")) || (deptDateTf.getText().equals("30") && deptMonthTf.getText().equals("02"))
                || (deptDateTf.getText().equals("31") && deptMonthTf.getText().equals("02")) || (deptDateTf.getText().equals("31") && deptMonthTf.getText().equals("04"))
                || (deptDateTf.getText().equals("31") && deptMonthTf.getText().equals("06")) || (deptDateTf.getText().equals("31") && deptMonthTf.getText().equals("09"))
                || (deptDateTf.getText().equals("31") && deptMonthTf.getText().equals("11")) || (arrDateTf.getText().equals("29") && arrMonthTf.getText().equals("02"))
                || (arrDateTf.getText().equals("30") && arrMonthTf.getText().equals("02")) || (arrDateTf.getText().equals("31") && arrMonthTf.getText().equals("02"))
                || (arrDateTf.getText().equals("31") && arrMonthTf.getText().equals("04")) || (arrDateTf.getText().equals("31") && arrMonthTf.getText().equals("06"))
                || (arrDateTf.getText().equals("31") && arrMonthTf.getText().equals("09")) || (arrDateTf.getText().equals("31") && arrMonthTf.getText().equals("11"))) {
            warningLbl.setText("Incorrect date format.");
        }

        
        else {
                 
        String datePosted = new SimpleDateFormat("dd-MM-yyyy").format(Calendar.getInstance().getTime());
        String departureAddress = departureTf.getText();
        String departureDateAndTime = deptDateTf.getText() + "-" + deptMonthTf.getText() + "-" + deptYearTf.getText() + "-" + deptHourTf.getText() + deptMinsTf.getText();
        String arrivalAddress = arrivalTf.getText();
        String arrivalDateAndTime = arrDateTf.getText() + "-" + arrMonthTf.getText() + "-" + arrYearTf.getText() + "-" + arrHourTf.getText() + arrMinsTf.getText();
        double distanceKM = Double.parseDouble(distanceTf.getText());
        int seatsAvailable = Integer.parseInt(noOfSeatsTf.getText());
        double pricePerSeat = Double.parseDouble(priceTf.getText());
        String description = descriptionTA.getText();
        boolean luggageAllowed = luggageCB.isSelected();
        boolean smokingAllowed = smokingCB.isSelected();
        boolean petAllowed = petsCB.isSelected();
        boolean chattyDriver = chattyCB.isSelected();
        boolean musicLover = musicLoverCB.isSelected();

        main.Trip t;
        main.Preferences p;

        t = new main.Trip(false, datePosted, departureAddress, departureDateAndTime, arrivalAddress, arrivalDateAndTime, distanceKM);
        p = new main.Preferences(seatsAvailable, pricePerSeat, luggageAllowed, smokingAllowed, petAllowed, chattyDriver, musicLover, description);

        cpdb.addTrip(t);
        cpdb.addPreferences(p);

        warningLbl.setText("Good job!");

        departureTf.setText("");
        deptDateTf.setText("");
        deptMonthTf.setText("");
        deptYearTf.setText("");
        deptHourTf.setText("");
        deptMinsTf.setText("");
        arrivalTf.setText("");
        arrDateTf.setText("");
        arrMonthTf.setText("");
        arrYearTf.setText("");
        arrHourTf.setText("");
        arrMinsTf.setText("");
        distanceTf.setText("");
        noOfSeatsTf.setText("");
        priceTf.setText("");
        descriptionTA.setText("");
        luggageCB.setSelected(false);
        smokingCB.setSelected(false);
        petsCB.setSelected(false);
        chattyCB.setSelected(false);
        musicLoverCB.setSelected(false);
        }
    }//GEN-LAST:event_addTripActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewTripGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewTripGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewTripGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewTripGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewTripGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTrip;
    private javax.swing.JLabel arrDateLbl;
    private javax.swing.JTextField arrDateTf;
    private javax.swing.JTextField arrHourTf;
    private javax.swing.JTextField arrMinsTf;
    private javax.swing.JTextField arrMonthTf;
    private javax.swing.JLabel arrTimeLbl;
    private javax.swing.JTextField arrYearTf;
    private javax.swing.JLabel arrivalLbl;
    private javax.swing.JTextField arrivalTf;
    private javax.swing.JCheckBox chattyCB;
    private javax.swing.JLabel daptDateLbl;
    private javax.swing.JLabel departureLbl;
    private javax.swing.JTextField departureTf;
    private javax.swing.JTextField deptDateTf;
    private javax.swing.JTextField deptHourTf;
    private javax.swing.JTextField deptMinsTf;
    private javax.swing.JTextField deptMonthTf;
    private javax.swing.JLabel deptTimeLbl;
    private javax.swing.JTextField deptYearTf;
    private javax.swing.JLabel descriptionLbl;
    private javax.swing.JTextArea descriptionTA;
    private javax.swing.JTextField distanceTf;
    private javax.swing.JPanel headerPnl;
    private javax.swing.JLabel heading1Lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JCheckBox luggageCB;
    private javax.swing.JCheckBox musicLoverCB;
    private javax.swing.JLabel nameLbl;
    private javax.swing.JLabel noOfSeatsLbl;
    private javax.swing.JTextField noOfSeatsTf;
    private javax.swing.JCheckBox petsCB;
    private javax.swing.JLabel preferencesLbl;
    private javax.swing.JLabel priceLbl;
    private javax.swing.JTextField priceTf;
    private javax.swing.JCheckBox smokingCB;
    private javax.swing.JLabel warningLbl;
    // End of variables declaration//GEN-END:variables
}
